# Generated by Django 5.1.4 on 2026-03-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spps',
            field=models.BooleanField(default=False, verbose_name='СППС'),
        ),
    ]
