# Generated by Django 5.1.4 on 2026-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('slide_type', models.CharField(choices=[('content', 'Контент'), ('image', 'Изображение'), ('poll', 'Опрос'), ('quiz', 'Викторина'), ('open_question', 'Открытый вопрос'), ('video', 'Видео')], default='content', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое')),
                ('image', models.FileField(blank=True, null=True, upload_to='lesson_images/%Y/%m/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', 'id'],
            },
        ),
    ]
