# Generated by Django 5.1.4 on 2026-02-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_media/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Медиафайл урока',
                'verbose_name_plural': 'Медиафайлы уроков',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
