# Generated by Django 5.1.4 on 2026-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('content', 'Контент'), ('image', 'Изображение'), ('poll', 'Опрос'), ('quiz', 'Викторина'), ('open_question', 'Открытый вопрос'), ('video', 'Видео'), ('form', 'Форма'), ('discussion', 'Доска обсуждений')], default='content', max_length=20, verbose_name='Тип'),
        ),
    ]
