# Generated by Django 5.1.4 on 2026-02-26 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list, verbose_name='Ответы')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='lessons.lessonsession', verbose_name='Сессия')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='lessons.slide', verbose_name='Слайд')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ на форму',
                'verbose_name_plural': 'Ответы на формы',
                'unique_together': {('session', 'slide', 'student')},
            },
        ),
    ]
