# Generated by Django 5.1.4 on 2026-02-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_formanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('content', 'Контент'), ('image', 'Изображение'), ('poll', 'Опрос'), ('quiz', 'Викторина'), ('open_question', 'Открытый вопрос'), ('video', 'Видео'), ('form', 'Форма'), ('discussion', 'Доска обсуждений'), ('vocab', 'Словарь')], default='content', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='VocabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=100, verbose_name='ID слова')),
                ('attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('correct', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('learned', models.BooleanField(default=False, verbose_name='Выучено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to='lessons.lessonsession', verbose_name='Сессия')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to='lessons.slide', verbose_name='Слайд')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по слову',
                'verbose_name_plural': 'Прогресс по словам',
                'unique_together': {('session', 'slide', 'student', 'word_id')},
            },
        ),
    ]
