# Generated by Django 5.1.4 on 2026-02-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_slide_vocab_vocabprogress'),
        ('school', '0010_schoolclass_curator_parentprofile_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(upload_to='textbooks/%Y/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=300, verbose_name='Оригинальное имя')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_classes', models.ManyToManyField(blank=True, related_name='textbooks', to='school.schoolclass', verbose_name='Классы')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbooks', to='school.subject', verbose_name='Предмет')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_textbooks', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Учебник',
                'verbose_name_plural': 'Учебники',
                'ordering': ['title'],
            },
        ),
    ]
