# Generated by Django 5.1.4 on 2026-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_textbook'),
        ('school', '0010_schoolclass_curator_parentprofile_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='school_classes',
        ),
        migrations.AddField(
            model_name='textbook',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, related_name='textbooks', to='school.gradelevel', verbose_name='Параллели'),
        ),
    ]
