# Generated by Django 5.1.4 on 2026-02-28 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_textbook_grade_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('content', 'Контент'), ('image', 'Изображение'), ('poll', 'Опрос'), ('quiz', 'Викторина'), ('open_question', 'Открытый вопрос'), ('video', 'Видео'), ('form', 'Форма'), ('discussion', 'Доска обсуждений'), ('vocab', 'Словарь'), ('textbook', 'Учебник')], default='content', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='TextbookAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('strokes', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_annotations', to='lessons.lessonsession')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_annotations', to='lessons.slide')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аннотация учебника',
                'verbose_name_plural': 'Аннотации учебника',
                'unique_together': {('session', 'slide', 'student', 'page_number')},
            },
        ),
    ]
