# Generated by Django 5.1.4 on 2026-03-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания')),
                ('time_note', models.CharField(blank=True, max_length=100, verbose_name='Время')),
                ('target_classes', models.CharField(blank=True, max_length=300, verbose_name='Классы')),
                ('organizers', models.CharField(blank=True, max_length=300, verbose_name='Организаторы')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='Ответственный')),
                ('helper', models.CharField(blank=True, max_length=300, verbose_name='Помощники')),
                ('event_type', models.CharField(blank=True, choices=[('holiday', 'Праздник'), ('teambuilding', 'Тимбилдинг'), ('cross_subject', 'Межпредметный проект'), ('subject', 'Предметный проект'), ('training', 'Обучение'), ('other', 'Другое')], max_length=50, verbose_name='Тип')),
                ('approved', models.CharField(blank=True, choices=[('yes', 'Согласовано'), ('no', 'Не согласовано'), ('rescheduled', 'Перенесено'), ('pending', 'Ожидает')], max_length=30, verbose_name='Согласовано')),
                ('cost', models.CharField(blank=True, max_length=200, verbose_name='Стоимость')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['date_start'],
            },
        ),
    ]
