# Generated by Django 5.1.4 on 2026-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holiday', 'Праздник'), ('teambuilding', 'Тимбилдинг'), ('meta_subject', 'Метапредметный проект'), ('cross_subject', 'Межпредметный проект'), ('subject', 'Предметный проект'), ('training', 'Обучение'), ('career_guidance', 'Профориентация'), ('other', 'Другое')], max_length=50, verbose_name='Тип'),
        ),
    ]
