# Generated by Django 5.1.4 on 2026-02-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Что оцениваем')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Поле оценки',
                'verbose_name_plural': 'Поля оценки',
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CuratorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сферы')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сфера развития',
                'verbose_name_plural': 'Сферы развития',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CuratorHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст подсказки')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='curator.curatorfield')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
            },
        ),
        migrations.CreateModel(
            name='CuratorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curator_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_reports', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Кураторский отчёт',
                'verbose_name_plural': 'Кураторские отчёты',
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='curatorfield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='curator.curatorsection'),
        ),
        migrations.CreateModel(
            name='CuratorReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='curator.curatorfield')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='curator.curatorreport')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'unique_together': {('report', 'field')},
            },
        ),
    ]
