# Generated by Django 5.1.4 on 2026-02-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_grouptask_assignees_alter_grouptask_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='message',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='created_by',
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('group', 'Группа'), ('direct', 'Личные сообщения')], default='group', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groups.chatmessage')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.chatroom')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=10)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_rel', to='groups.chatroom')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(default=0, verbose_name='Размер')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME-тип')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='groups.chatmessage')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='GroupTask',
        ),
    ]
