# Generated by Django 5.1.4 on 2026-03-07 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_chatmessage_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChatRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_cooldown', models.PositiveIntegerField(default=0, help_text='0 — без ограничений', verbose_name='Пауза между сообщениями (сек)')),
                ('muted_until', models.DateTimeField(blank=True, null=True, verbose_name='Мьют до')),
                ('no_links', models.BooleanField(default=False, verbose_name='Запрет ссылок')),
                ('no_files', models.BooleanField(default=False, verbose_name='Запрет файлов')),
                ('no_polls', models.BooleanField(default=False, verbose_name='Запрет опросов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_chat_restrictions', to=settings.AUTH_USER_MODEL, verbose_name='Установил')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_restriction', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ограничение в чате',
                'verbose_name_plural': 'Ограничения в чате',
            },
        ),
    ]
