# Generated by Django 5.1.4 on 2026-02-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0004_task_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_submissions', to='tasks.task'),
        ),
    ]
