# Generated by Django 5.1.4 on 2026-02-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_slide_slide_type_textbookannotation'),
        ('projects', '0002_assignmentsubmission_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignments', to='lessons.lesson', verbose_name='Урок'),
        ),
    ]
