# Generated by Django 5.1.4 on 2026-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectassignment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
