# Generated by Django 5.1.4 on 2026-02-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выходной',
                'verbose_name_plural': 'Выходные',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctps', to='school.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctps', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'КТП',
                'verbose_name_plural': 'КТП',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=500, verbose_name='Тема')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('homework', models.TextField(blank=True, default='', verbose_name='Домашнее задание')),
                ('resources', models.JSONField(blank=True, default=list, verbose_name='Ссылки на материалы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ctp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='ktp.ctp')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order'],
            },
        ),
    ]
