# Generated by Django 5.1.4 on 2026-02-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='topic_files/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ktp.topic')),
            ],
            options={
                'verbose_name': 'Файл темы',
                'verbose_name_plural': 'Файлы тем',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
