# Generated by Django 5.1.4 on 2026-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0003_topic_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата'),
        ),
    ]
