# Generated by Django 5.1.4 on 2026-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0004_alter_topic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='additional_resources',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные ресурсы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='topic',
            name='individual_folder',
            field=models.TextField(blank=True, default='', verbose_name='Индивид. папка ученика'),
        ),
        migrations.AddField(
            model_name='topic',
            name='ksp',
            field=models.TextField(blank=True, default='', verbose_name='КСП'),
        ),
        migrations.AddField(
            model_name='topic',
            name='presentation_link',
            field=models.TextField(blank=True, default='', verbose_name='Ссылка на презентацию'),
        ),
        migrations.AddField(
            model_name='topic',
            name='self_study_links',
            field=models.TextField(blank=True, default='', verbose_name='Ссылки на самообучение'),
        ),
    ]
