# Generated by Django 5.1.4 on 2026-03-11 15:18
# Data migration: normalize empty strings before field type change.

from django.db import migrations


def normalize_link_fields(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE ktp_topic
            SET self_study_links = '[]'
            WHERE self_study_links IS NULL OR self_study_links = '';
        """)
        cursor.execute("""
            UPDATE ktp_topic
            SET additional_resources = '[]'
            WHERE additional_resources IS NULL OR additional_resources = '';
        """)
        cursor.execute("""
            UPDATE ktp_topic
            SET individual_folder = '[]'
            WHERE individual_folder IS NULL OR individual_folder = '';
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0006_schoolbreak'),
    ]

    operations = [
        migrations.RunPython(normalize_link_fields, migrations.RunPython.noop),
    ]
