# Generated by Django 5.1.4 on 2026-03-11 15:18
# Schema migration: change TextField → JSONField for link fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0007b_normalize_nonjson_link_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='additional_resources',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные ресурсы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='individual_folder',
            field=models.JSONField(blank=True, default=list, verbose_name='Индивид. папка ученика'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='self_study_links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на самообучение'),
        ),
    ]
