# Generated by Django 5.1.4 on 2026-03-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0010_schoolclass_curator_parentprofile_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('fact', models.TextField(verbose_name='Факт')),
                ('lesson', models.CharField(blank=True, max_length=100, verbose_name='На каком уроке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by_spps', models.BooleanField(default=False, verbose_name='Прочитано СППС')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yellow_entries', to='school.studentprofile', verbose_name='Ученик')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellow_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Кто подал')),
            ],
            options={
                'verbose_name': 'Запись жёлтого списка',
                'verbose_name_plural': 'Записи жёлтого списка',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YellowListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellow_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yellow_list.yellowlistentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Комментарий СППС',
                'verbose_name_plural': 'Комментарии СППС',
                'ordering': ['created_at'],
            },
        ),
    ]
