# Generated by Django 5.1.4 on 2026-02-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к доработке'),
        ),
    ]
