# Generated by Django 5.1.4 on 2026-02-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_room_schedulelesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='teacher',
        ),
    ]
