# Generated by Django 5.1.4 on 2026-02-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_classsubject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_lessons', to='school.classgroup'),
        ),
    ]
