# Generated by Django 5.1.4 on 2026-02-22 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_classsubject_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AhoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('work_type', models.CharField(choices=[('furniture', 'Ремонт мебели'), ('rooms', 'Ремонт помещений'), ('plumbing', 'Ремонт сантехники'), ('other', 'Прочее')], max_length=20, verbose_name='Вид работ')),
                ('urgency', models.CharField(blank=True, choices=[('5', 'Пять звёзд'), ('4', 'Четыре звезды'), ('3', 'Три звезды'), ('2', 'Две звезды'), ('1', 'Одна звезда')], max_length=1, verbose_name='Срочно')),
                ('importance', models.CharField(blank=True, choices=[('5', 'Пять звёзд'), ('4', 'Четыре звезды'), ('3', 'Три звезды'), ('2', 'Две звезды'), ('1', 'Одна звезда')], max_length=1, verbose_name='Важно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aho_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка АХО',
                'verbose_name_plural': 'Заявки АХО',
                'ordering': ['-created_at'],
            },
        ),
    ]
