# Generated by Django 5.1.4 on 2026-02-22 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_aho_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_classes', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
    ]
