# Generated by Django 5.1.4 on 2026-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_schoolclass_curator_parentprofile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
    ]
