# Generated by Django 5.1.4 on 2026-03-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_studentprofile_personal_file_number'),
        ('school', '0013_lessontimeslot_initial_data'),
    ]

    operations = [
    ]
